### ISSUE TITLE
the relative paths are Windows-specific (not cross-platform)

### ISSUE THREAD

**Issue by argriffing** [danielmoney/GeLL#2]
https://github.com/danielmoney/GeLL/blob/master/test/Likelihood/LikelihoodTest.java#L58

**Comment by danielmoney** [comment]
OK, that one appears to be am error on my part - I know Java would allow you to use forward slashes on windows but didn't realise you couldn't do the reverse (I just learnt that).  As I was developing on Windows I hadn't noticed this.  Will fix this as well, although again as a test it shouldn't stop you using the library.

**Comment by danielmoney** [comment]
Should now be fixed.
