### ISSUE TITLE
GeLL driver examples on github?

### ISSUE THREAD

**Issue by argriffing** [danielmoney/GeLL#3]
I see these only on the Holder lab web page.

**Comment by danielmoney** [comment]
I'm marked this on won't fix - at least for now.  They are currently part of a different netbeans project (I forget why I did this but I know it made sense at the time) so adding them to this repository would be difficult.  As I don't see any extra advantage to them being on git as well I'd prefer not to go through the hassle of setting it up.  If other people would prefer them to be here as well then I'll reconsider.
